# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_kmp_llvm
alsa-lib=1.2.8=h166bdaf_0
aom=3.4.0=h27087fc_1
appdirs=1.4.4=pyh9f0ad1d_0
attr=2.5.1=h166bdaf_1
binutils_impl_linux-64=2.36.1=h193b22a_2
binutils_linux-64=2.36=hf3e587d_10
blas=2.116=openblas
blas-devel=3.9.0=16_linux64_openblas
blosc=1.21.1=h83bc5f7_3
boost-cpp=1.74.0=h75c5d50_8
brotli=1.0.9=h166bdaf_9
brotli-bin=1.0.9=h166bdaf_9
brotlipy=0.7.0=py310h5764c6d_1005
bzip2=1.0.8=h7f98852_4
c-ares=1.18.1=h7f98852_0
ca-certificates=2023.11.17=hbcca054_0
certifi=2023.11.17=pyhd8ed1ab_0
cffi=1.15.1=py310h255011f_0
charset-normalizer=2.1.1=pyhd8ed1ab_0
cloudpickle=3.0.0=pyhd8ed1ab_0
contourpy=1.0.5=pypi_0
cryptography=39.0.2=py310h34c0648_0
curl=7.86.0=h2283fc2_1
cycler=0.11.0=pyhd8ed1ab_0
cython=3.0.7=py310hc6cd4ac_0
dbus=1.13.6=h5008d03_3
double-conversion=3.2.0=h27087fc_1
eigen=3.4.0=h4bd325d_0
expat=2.5.0=hcb278e6_1
fenics-basix=0.5.0=py310hbf28c38_0
fenics-dolfinx=0.5.1=py310h0d9d84b_100
fenics-ffcx=0.5.0=pyhb871ab6_1
fenics-libbasix=0.5.0=heb3b609_0
fenics-libdolfinx=0.5.1=h6b5d60a_100
fenics-ufcx=0.5.0=hb871ab6_1
fenics-ufl=2022.2.0=pyhd8ed1ab_0
ffmpeg=4.4.2=gpl_hfe78399_107
fftw=3.3.10=mpi_mpich_h3e343da_5
fltk=1.3.8=h83e168f_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=hab24e00_0
fontconfig=2.14.2=h14ed4e7_0
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=0
fonttools=4.37.4=pypi_0
freeimage=3.18.0=h530e30e_10
freetype=2.12.1=hca18f0e_0
gcc_impl_linux-64=10.4.0=h7ee1905_16
gcc_linux-64=10.4.0=h9215b83_10
getfem=5.4.2=py310hd4e0858_4
gettext=0.21.1=h27087fc_0
gl2ps=1.4.2=h0708190_0
glew=2.1.0=h9c3ff4c_2
glib=2.74.1=h6239696_0
glib-tools=2.74.1=h6239696_0
gmp=6.2.1=h58526e2_0
gmsh=4.11.0=hc719622_0
gnutls=3.7.8=hf3e180e_0
gst-plugins-base=1.21.3=h4243ec0_1
gstreamer=1.21.3=h25f0c4b_1
gstreamer-orc=0.4.33=h166bdaf_0
gxx_impl_linux-64=10.4.0=h7ee1905_16
gxx_linux-64=10.4.0=h6e491c6_10
hdf4=4.2.15=h9772cbc_4
hdf5=1.12.1=mpi_mpich_h5d83325_4
hypre=2.25.0=mpi_mpich_hed3a557_0
icu=70.1=h27087fc_0
idna=3.4=pyhd8ed1ab_0
imageio=2.22.0=pyhfa7a67d_0
imath=3.1.6=h6239696_1
jack=1.9.22=h11f4161_0
jinja2=3.1.3=pyhd8ed1ab_0
jpeg=9e=h166bdaf_2
jsoncpp=1.9.5=h4bd325d_1
jxrlib=1.1=h7f98852_2
kernel-headers_linux-64=2.6.32=he073ed8_15
keyutils=1.6.1=h166bdaf_0
kiwisolver=1.4.4=py310hbf28c38_1
krb5=1.19.3=h08a2579_0
lame=3.100=h166bdaf_1002
lcms2=2.12=hddcbb42_0
ld_impl_linux-64=2.36.1=hea4e1c9_2
lerc=4.0.0=h27087fc_0
libadios2=2.8.3=mpi_mpich_h81ddebc_1
libblas=3.9.0=16_linux64_openblas
libbrotlicommon=1.0.9=h166bdaf_9
libbrotlidec=1.0.9=h166bdaf_9
libbrotlienc=1.0.9=h166bdaf_9
libcap=2.66=ha37c62d_0
libcblas=3.9.0=16_linux64_openblas
libclang=15.0.7=default_had23c3d_1
libclang13=15.0.7=default_h3e3d535_1
libcups=2.3.3=h3e49a29_2
libcurl=7.86.0=h2283fc2_1
libdb=6.2.32=h9c3ff4c_0
libdeflate=1.14=h166bdaf_0
libdrm=2.4.113=h166bdaf_0
libedit=3.1.20191231=he28a2e2_2
libev=4.33=h516909a_1
libevent=2.1.10=h28343ad_4
libexpat=2.5.0=hcb278e6_1
libffi=3.4.2=h7f98852_5
libflac=1.4.2=h27087fc_0
libgcc-devel_linux-64=10.4.0=h74af60c_16
libgcc-ng=12.1.0=h8d9b700_16
libgcrypt=1.10.1=h166bdaf_0
libgfortran-ng=12.1.0=h69a702a_16
libgfortran5=12.1.0=hdcd56e2_16
libglib=2.74.1=h7a41b64_0
libglu=9.0.0=he1b5a44_1001
libgomp=12.1.0=h8d9b700_16
libgpg-error=1.46=h620e276_0
libiconv=1.17=h166bdaf_0
libidn2=2.3.3=h166bdaf_0
liblapack=3.9.0=16_linux64_openblas
liblapacke=3.9.0=16_linux64_openblas
libllvm14=14.0.6=he0ac6c6_0
libllvm15=15.0.7=hadd5161_1
libnetcdf=4.8.1=mpi_mpich_hcdf9059_2
libnghttp2=1.52.0=h61bc06f_0
libnsl=2.0.0=h7f98852_0
libogg=1.3.4=h7f98852_1
libopenblas=0.3.21=pthreads_h78a6416_3
libopus=1.3.1=h7f98852_1
libpciaccess=0.16=h516909a_0
libpng=1.6.39=h753d276_0
libpq=15.1=h67c24c5_1
libraw=0.20.2=h10796ff_1
libsanitizer=10.4.0=hde28e3b_16
libsndfile=1.1.0=hcb278e6_1
libsodium=1.0.18=h36c2ea0_1
libsqlite=3.40.0=h753d276_0
libssh2=1.10.0=hf14f497_3
libstdcxx-devel_linux-64=10.4.0=h74af60c_16
libstdcxx-ng=12.1.0=ha89aaad_16
libsystemd0=252=h2a991cd_0
libtasn1=4.19.0=h166bdaf_0
libtheora=1.1.1=h7f98852_1005
libtiff=4.4.0=h55922b4_4
libtool=2.4.6=h9c3ff4c_1008
libudev1=253=h0b41bf4_0
libunistring=0.9.10=h7f98852_0
libuuid=2.32.1=h7f98852_1000
libva=2.16.0=h166bdaf_0
libvorbis=1.3.7=h9c3ff4c_0
libvpx=1.11.0=h9c3ff4c_3
libwebp-base=1.2.4=h166bdaf_0
libxcb=1.13=h7f98852_1004
libxkbcommon=1.0.3=he3ba5ed_0
libxml2=2.10.3=hca2bb57_4
libzip=1.9.2=hc929e4a_1
libzlib=1.2.13=h166bdaf_4
llvm-openmp=16.0.0=h417c0b6_0
loguru=0.6.0=py310hff52083_1
lz4-c=1.9.3=h9c3ff4c_1
markdown-it-py=2.2.0=pypi_0
markupsafe=2.1.4=py310h2372a71_0
matplotlib=3.7.2=py310hff52083_0
matplotlib-base=3.7.2=py310hf38f957_0
mdurl=0.1.2=pyhd8ed1ab_0
memory_profiler=0.61.0=pyhd8ed1ab_0
meshio=5.3.4=pypi_0
metis=5.1.0=h58526e2_1006
mpfr=4.1.0=h9202a9a_1
mpg123=1.31.3=hcb278e6_0
mpi=1.0=mpich
mpi4py=3.1.3=py310h37cc914_2
mpich=4.0.2=h846660c_100
mumps-include=5.2.1=ha770c72_11
mumps-mpi=5.2.1=h7ee95aa_11
mumps-seq=5.2.1=h2104b81_11
munkres=1.1.4=pyh9f0ad1d_0
mysql-common=8.0.32=ha901b37_1
mysql-libs=8.0.32=hd7da12d_1
ncurses=6.3=h27087fc_1
nettle=3.8.1=hc379101_1
ninja=1.11.0=h924138e_0
nspr=4.35=h27087fc_0
nss=3.89=he45b914_0
numpy=1.23.3=py310h53a5b5f_0
occt=7.6.3=h665cfa0_0
openblas=0.3.21=pthreads_h320a7e8_3
openexr=3.1.5=he0ac6c6_1
openh264=2.3.0=h27087fc_0
openjpeg=2.5.0=h7d73246_1
openssl=3.2.1=hd590300_0
p11-kit=0.24.1=hc5aa10d_0
packaging=21.3=pypi_0
parmetis=4.0.3=h2a9763c_1005
pcre2=10.37=hc3806b6_1
petsc=3.17.3=real_h6ce3b2e_100
petsc4py=3.17.3=real_h5faf7bb_101
pillow=9.2.0=py310hbd86126_2
pip=22.2.2=pyhd8ed1ab_0
ply=3.11=py_1
pooch=1.6.0=pyhd8ed1ab_0
portaudio=19.6.0=h583fa2b_7
proj=9.0.1=h93bde94_1
psutil=5.9.8=py310h2372a71_0
pthread-stubs=0.4=h36c2ea0_1001
ptscotch=6.0.9=hb499603_2
pugixml=1.11.4=h9c3ff4c_0
pulseaudio=16.1=h126f2b6_0
pybind11=2.10.1=pypi_0
pycparser=2.21=pyhd8ed1ab_0
pygments=2.14.0=pypi_0
pympler=1.0.1=pyhd8ed1ab_0
pynvml=11.4.1=pyhd8ed1ab_0
pyopenssl=23.0.0=pyhd8ed1ab_0
pyparsing=3.0.9=pyhd8ed1ab_0
pyqt=5.15.7=py310hab646b1_3
pyqt5-sip=12.11.0=py310heca2aa9_3
pysocks=1.7.1=pyha2e5f31_6
python=3.10.9=he550d4f_0_cpython
python-dateutil=2.8.2=pyhd8ed1ab_0
python-gmsh=4.11.0=h57928b3_0
python_abi=3.10=2_cp310
pyvista=0.38.1=pyhd8ed1ab_0
qhull=2020.2=h4bd325d_2
qt-main=5.15.6=hafeba50_4
rapidjson=1.1.0=he1b5a44_1002
readline=8.1.2=h0f457ee_0
requests=2.28.2=pyhd8ed1ab_0
rich=13.3.3=pypi_0
scalapack=2.2.0=hd931219_1
scalene=1.5.33.1=py310hc6cd4ac_0
scipy=1.10.1=py310h8deb116_0
scooby=0.6.0=pyhd8ed1ab_0
scotch=6.0.9=hb2e6521_2
setuptools=65.4.0=pyhd8ed1ab_0
sip=6.7.11=py310hc6cd4ac_0
six=1.16.0=pyh6c4a22f_0
slepc=3.17.1=real_ha2e80f3_102
slepc4py=3.17.1=real_h7df52cc_103
snappy=1.1.9=hbd366e4_1
sqlite=3.40.0=h4ff8645_0
suitesparse=5.10.1=h9e50725_1
superlu=5.2.2=h00795ac_0
superlu_dist=7.2.0=h25dcc4a_0
svt-av1=1.2.1=h27087fc_0
sysroot_linux-64=2.12=he073ed8_15
tbb=2021.6.0=h924138e_0
tbb-devel=2021.6.0=h924138e_0
tk=8.6.12=h27826a3_0
toml=0.10.2=pyhd8ed1ab_0
tomli=2.0.1=pyhd8ed1ab_0
tornado=6.3.2=py310h2372a71_0
typing_extensions=4.3.0=pyha770c72_0
tzdata=2022d=h191b570_0
unicodedata2=15.0.0=py310h5764c6d_0
urllib3=1.26.14=pyhd8ed1ab_0
utfcpp=3.2.1=ha770c72_0
vtk=9.1.0=qt_py310hb71b3df_211
wheel=0.37.1=pyhd8ed1ab_0
x264=1!164.3095=h166bdaf_2
x265=3.5=h924138e_3
xcb-util=0.4.0=h166bdaf_0
xcb-util-image=0.4.0=h166bdaf_0
xcb-util-keysyms=0.4.0=h166bdaf_0
xcb-util-renderutil=0.3.9=h166bdaf_0
xcb-util-wm=0.4.1=h166bdaf_0
xorg-fixesproto=5.0=h7f98852_1002
xorg-kbproto=1.0.7=h7f98852_1002
xorg-libice=1.0.10=h7f98852_0
xorg-libsm=1.2.3=hd9c2040_1000
xorg-libx11=1.7.2=h7f98852_0
xorg-libxau=1.0.9=h7f98852_0
xorg-libxdmcp=1.1.3=h7f98852_0
xorg-libxext=1.3.4=h7f98852_1
xorg-libxfixes=5.0.3=h7f98852_1004
xorg-libxmu=1.1.3=h7f98852_0
xorg-libxrender=0.9.10=h7f98852_1003
xorg-libxt=1.2.1=h7f98852_2
xorg-renderproto=0.11.1=h7f98852_1002
xorg-xextproto=7.3.0=h7f98852_1002
xorg-xproto=7.0.31=h7f98852_1007
xtensor=0.24.3=h924138e_0
xtl=0.7.4=h4bd325d_0
xz=5.2.6=h166bdaf_0
yaml=0.2.5=h7f98852_2
zeromq=4.3.4=h9c3ff4c_1
zfp=0.5.5=h9c3ff4c_8
zlib=1.2.13=h166bdaf_4
zstd=1.5.2=h6239696_4
